version: 1
disable-existing-loggers: False
formatters:
    simpleFormatter:
        format: '%(asctime)s %(message)s'
        datefmt: '%Y/%m/%d %H:%M:%S'

    progressFormatter:
        format: '%(asctime)s %(message)s'
        datefmt: '%H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        formatter: progressFormatter
        level: INFO
        stream: ext://sys.stdout
    file:
        class : logging.FileHandler
        formatter: simpleFormatter
        level: DEBUG
        filename: summariser-log.txt

loggers:
    consoleLogger:
        level: INFO
        handlers: [console]
    fileLogger:
        level: DEBUG
        handlers: [file]

root:
    level: DEBUG
    handlers: [console, file]